name: "Chromatic"

on:
  pull_request:
    branches: [main] 

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        run: npx chromatic --exit-once-uploaded
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
